### ISSUE TITLE
how to save workflow as png image file, just like your workflows

### ISSUE THREAD

**Issue by dwgeneral** [yuyou-dev/workflow#3]
I found a script called workflow2png here. Is there a more convenient way to achieve it?
https://colab.research.google.com/drive/1hQMjNUdhMQ3rw1Wcm3_umvmOMeS_K4s8#scrollTo=llbal5zlANoH&uniqifier=1

**Comment by yuyou-dev** [comment]
![WX20240713-192746@2x](https://github.com/user-attachments/assets/7951a0c7-8d1b-4737-acb3-963ce65127a3)
Right click here
